/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.the_vending_machine;

import java.awt.*;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import static java.lang.Thread.sleep;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author premsharaan
 */
public class StaffMainMenu extends javax.swing.JFrame {

    //This variable is for setting project folder directory
    private String projectDir;

    /**
     * Creates new form StaffMainMenu
     */
    public StaffMainMenu() {
        initComponents();
        initGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlManageItems = new javax.swing.JPanel();
        lblStock = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlModifyStaff = new javax.swing.JPanel();
        lblModify = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlAddStaff = new javax.swing.JPanel();
        lblRegisterStaff = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblMainMenu = new javax.swing.JLabel();
        pnlHistory = new javax.swing.JPanel();
        lblHistory = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblVending = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Main Menu");
        setMaximumSize(new java.awt.Dimension(1440, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        pnlManageItems.setBackground(new java.awt.Color(102, 0, 0));
        pnlManageItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlManageItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlManageItemsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlManageItemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlManageItemsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlManageItemsMousePressed(evt);
            }
        });

        lblStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStockMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Manage Items");

        javax.swing.GroupLayout pnlManageItemsLayout = new javax.swing.GroupLayout(pnlManageItems);
        pnlManageItems.setLayout(pnlManageItemsLayout);
        pnlManageItemsLayout.setHorizontalGroup(
            pnlManageItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlManageItemsLayout.setVerticalGroup(
            pnlManageItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageItemsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlManageItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageItemsLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManageItemsLayout.createSequentialGroup()
                        .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pnlModifyStaff.setBackground(new java.awt.Color(102, 0, 0));
        pnlModifyStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlModifyStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlModifyStaffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlModifyStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlModifyStaffMouseExited(evt);
            }
        });

        lblModify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModifyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModifyMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modify Staff Details");

        javax.swing.GroupLayout pnlModifyStaffLayout = new javax.swing.GroupLayout(pnlModifyStaff);
        pnlModifyStaff.setLayout(pnlModifyStaffLayout);
        pnlModifyStaffLayout.setHorizontalGroup(
            pnlModifyStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyStaffLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblModify, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        pnlModifyStaffLayout.setVerticalGroup(
            pnlModifyStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlModifyStaffLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(lblModify, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlAddStaff.setBackground(new java.awt.Color(102, 0, 0));
        pnlAddStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAddStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddStaffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddStaffMouseExited(evt);
            }
        });

        lblRegisterStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterStaffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegisterStaffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegisterStaffMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Add Staff");

        javax.swing.GroupLayout pnlAddStaffLayout = new javax.swing.GroupLayout(pnlAddStaff);
        pnlAddStaff.setLayout(pnlAddStaffLayout);
        pnlAddStaffLayout.setHorizontalGroup(
            pnlAddStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStaffLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblRegisterStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAddStaffLayout.setVerticalGroup(
            pnlAddStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegisterStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddStaffLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(35, 35, 35))
        );

        lblTime.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 204, 204));
        lblTime.setText("time");

        lblDate.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 204, 204));
        lblDate.setText("date");

        lblMainMenu.setFont(new java.awt.Font(".SF NS Text", 1, 28)); // NOI18N
        lblMainMenu.setForeground(new java.awt.Color(255, 204, 204));
        lblMainMenu.setText(" Staff Main Menu");

        pnlHistory.setBackground(new java.awt.Color(102, 0, 0));
        pnlHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHistoryMouseExited(evt);
            }
        });

        lblHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHistoryMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("View Purchase");

        javax.swing.GroupLayout pnlHistoryLayout = new javax.swing.GroupLayout(pnlHistory);
        pnlHistory.setLayout(pnlHistoryLayout);
        pnlHistoryLayout.setHorizontalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHistoryLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        pnlHistoryLayout.setVerticalGroup(
            pnlHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHistoryLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlManageItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAddStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlModifyStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHistory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblTime)
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pnlManageItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(pnlAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(pnlModifyStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(pnlHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 900));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));

        btnLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnLogout.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 15)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log Out");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tblItem.setBackground(new java.awt.Color(255, 255, 255));
        tblItem.setFont(new java.awt.Font("Geeza Pro", 1, 13)); // NOI18N
        tblItem.setForeground(new java.awt.Color(0, 0, 0));
        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Item Price", "Item Quantity"
            }
        ));
        tblItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblItem.setRowHeight(45);
        tblItem.setSelectionBackground(new java.awt.Color(51, 0, 0));
        tblItem.setSelectionForeground(new java.awt.Color(255, 204, 204));
        tblItem.setSurrendersFocusOnKeystroke(true);
        jScrollPane2.setViewportView(tblItem);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Beirut", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Vending Machine Items");

        txtUsername.setBackground(new java.awt.Color(102, 0, 0));
        txtUsername.setFont(new java.awt.Font("Devanagari Sangam MN", 3, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap(419, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVending))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(lblVending)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(131, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 0, 1120, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Staff Logout!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            clearStaffSession();
            new MainVMFram().setVisible(true);
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void pnlAddStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddStaffMouseExited
        resetPnl2Color();
    }//GEN-LAST:event_pnlAddStaffMouseExited

    private void pnlAddStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddStaffMouseEntered
        setPnl2Color();
    }//GEN-LAST:event_pnlAddStaffMouseEntered

    private void pnlAddStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddStaffMouseClicked
      
        new StaffRegister().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_pnlAddStaffMouseClicked

    private void lblRegisterStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterStaffMouseExited
        resetPnl2Color();
    }//GEN-LAST:event_lblRegisterStaffMouseExited

    private void lblRegisterStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterStaffMouseEntered
        setPnl2Color();
    }//GEN-LAST:event_lblRegisterStaffMouseEntered

    private void lblRegisterStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterStaffMouseClicked
        
        new StaffRegister().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegisterStaffMouseClicked

    private void pnlModifyStaffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlModifyStaffMouseExited
        resetPnl3Color();
    }//GEN-LAST:event_pnlModifyStaffMouseExited

    private void pnlModifyStaffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlModifyStaffMouseEntered
        setPnl3Color();
    }//GEN-LAST:event_pnlModifyStaffMouseEntered

    private void pnlModifyStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlModifyStaffMouseClicked
        
        new ManageStaffDetails().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlModifyStaffMouseClicked

    private void lblModifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyMouseExited
        resetPnl3Color();
    }//GEN-LAST:event_lblModifyMouseExited

    private void lblModifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyMouseEntered
        setPnl3Color();
    }//GEN-LAST:event_lblModifyMouseEntered

    private void lblModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyMouseClicked
       
        new ManageStaffDetails().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_lblModifyMouseClicked

    private void pnlManageItemsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageItemsMousePressed

    }//GEN-LAST:event_pnlManageItemsMousePressed

    private void pnlManageItemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageItemsMouseExited
        resetPnl1Color();
    }//GEN-LAST:event_pnlManageItemsMouseExited

    private void pnlManageItemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageItemsMouseEntered
        setPnl1Color();
    }//GEN-LAST:event_pnlManageItemsMouseEntered

    private void pnlManageItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlManageItemsMouseClicked
        
        new VenAddStock().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlManageItemsMouseClicked

    private void lblStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockMouseExited
        resetPnl1Color();
    }//GEN-LAST:event_lblStockMouseExited

    private void lblStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockMouseEntered
        setPnl1Color();
    }//GEN-LAST:event_lblStockMouseEntered

    private void lblStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockMouseClicked
       
        new VenAddStock().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblStockMouseClicked

    private void lblHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblHistoryMouseClicked

    private void lblHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoryMouseEntered
        setPnl4Color();
    }//GEN-LAST:event_lblHistoryMouseEntered

    private void lblHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistoryMouseExited
       resetPnl4Color();
    }//GEN-LAST:event_lblHistoryMouseExited

    private void pnlHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHistoryMouseClicked
          
        new PurchaseHistory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlHistoryMouseClicked

    private void pnlHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHistoryMouseEntered
         setPnl4Color();
    }//GEN-LAST:event_pnlHistoryMouseEntered

    private void pnlHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHistoryMouseExited
       resetPnl4Color();
    }//GEN-LAST:event_pnlHistoryMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  //This sets the frame customization
                  StaffMainMenu frame = new StaffMainMenu();
                  frame.setVisible(true);
                  frame.setResizable(false);
              
            }
        });
    }

    //This sets different background color while hovering on it
    public void setPnl1Color() {
        pnlManageItems.setBackground(new Color(153, 0, 0));
    }

    public void setPnl2Color() {
        pnlAddStaff.setBackground(new Color(153, 0, 0));
    }

    public void setPnl3Color() {
        pnlModifyStaff.setBackground(new Color(153, 0, 0));
    }

      public void setPnl4Color() {
        pnlHistory.setBackground(new Color(153, 0, 0));
    }
    
    //This sets the panel back to normal color
    public void resetPnl1Color() {
        pnlManageItems.setBackground(new Color(102, 0, 0));
    }

    public void resetPnl2Color() {
        pnlAddStaff.setBackground(new Color(102, 0, 0));
    }

    public void resetPnl3Color() {
        pnlModifyStaff.setBackground(new Color(102, 0, 0));
    }
    
    
     public void resetPnl4Color() {
        pnlHistory.setBackground(new Color(102, 0, 0));
    }


    //This method is to delete a temporary staff session that has been created during verification
    private void clearStaffSession() {
        try {
            // This sets the directory of the project
            projectDir = System.getProperty("user.dir") + "//db_txtFiles//";
            File staffCache = new File(projectDir + "StaffCache.txt");
            if (staffCache.exists()) {
                staffCache.delete();
            }
        } catch (Exception ex) {

        }
    }

    //SThis styles the username text panel
    private void styleUsernameField() {
        txtUsername.setHorizontalAlignment(JTextField.CENTER);
        txtUsername.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        txtUsername.setEditable(false);
    }

    //This sets current system date
    private void CurrentDate() {
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("E, MMM dd, yyyy");
        String currentdate = myDateObj.format(myFormatObj);
        String date = currentdate.toString();
        lblDate.setText(date);
    }

    //This sets current system time
    private void CurrentTime() {
        Thread time = new Thread() {
            public void run() {
                try {
                    for (;;) {
                        Calendar cal = new GregorianCalendar();
                        int day = cal.get(Calendar.AM_PM);
                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);
                        String am_pm = "am_pm";
                        if (day == 0) {
                            am_pm = "AM";
                        } else {
                            am_pm = "PM";
                        }
                        lblTime.setText(hour + ":" + minute + ":" + second + " " + am_pm);
                        sleep(1000);
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainVMFram.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        };

        time.start();
    }
    
    
  //This method is to set the image icon
    private void getImgIcon() {
        projectDir = System.getProperty("user.dir") + "//Images//";
        ImageIcon imageHome = new ImageIcon(projectDir + "home.png");
        Image imgHome = imageHome.getImage();
        lblMainMenu.setIcon(new ImageIcon(imgHome));

        ImageIcon imageStock = new ImageIcon(projectDir + "stock.png");
        Image imgStock = imageStock.getImage();
        lblStock.setIcon(new ImageIcon(imgStock));

        ImageIcon imageRegister = new ImageIcon(projectDir + "registerResized.png");
        Image imgRegister = imageRegister.getImage();
        lblRegisterStaff.setIcon(new ImageIcon(imgRegister));

        ImageIcon imageModifyStaff = new ImageIcon(projectDir + "modifyResized.png");
        Image imgModifyStaff = imageModifyStaff.getImage();
        lblModify.setIcon(new ImageIcon(imgModifyStaff));

        ImageIcon imageVending = new ImageIcon(projectDir + "vendingmachine.jpg");
        Image imgVending = imageVending.getImage();
        lblVending.setIcon(new ImageIcon(imgVending));

          ImageIcon imageHistory = new ImageIcon(projectDir + "history.png");
          Image imgHistory= imageHistory.getImage();
          lblHistory.setIcon(new ImageIcon(imgHistory));
       
    }

    
    //This gets the item details from the textfile to the tabel
       private void getItemDetails() {
        projectDir = System.getProperty("user.dir") + "//db_txtFiles//";
        File staffDetails = new File(projectDir + "StockItem.txt");
        try {
            FileReader fr = new FileReader(staffDetails);
            BufferedReader br = new BufferedReader(fr);
            //This sets the table into a table model
            DefaultTableModel model = (DefaultTableModel) tblItem.getModel();

            //This is to  get line  by line from the text file
            Object[] tableLines = br.lines().toArray();
            //This is to retrieve the content from the lines in the text file and set the content in to the jtable
            for (int i = 0; i < tableLines.length; i++) {
                String detailsline = tableLines[i].toString().trim();
                String[] staffDataRow = detailsline.split(":");
                model.addRow(staffDataRow);
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageStaffDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

       
       
      //This method is to get username and display it in textfield
    private void getUsername() {
       String[] staffCredential;
        try {
            // This sets the directory of the project
            projectDir = System.getProperty("user.dir") + "//db_txtFiles//";
            // This sets the file which going to be accessed
            File cacheFile = new File(projectDir + "StaffCache.txt");
            if (!cacheFile.exists()) {
                cacheFile.createNewFile();
            }
            Scanner searchUsername = new Scanner(cacheFile);
            // Read till last line of file
            while (searchUsername.hasNext()) {
                // Read the next line.
                String inputUsername = searchUsername.nextLine();
                // Split the details by using the colon and store in an array.
                staffCredential = inputUsername.split(":");
                txtUsername.setText("Welcome   " + staffCredential[0]);
            }
            searchUsername.close();
        } catch (Exception ex) {

        }
    }
  
       
       
    public void initGUI() {
     
        //This will get the image from the file
        getImgIcon();

        //This sets the button to not focus
        btnLogout.setFocusable(false);
        txtUsername.setFocusable(false);
        tblItem.setFocusable(false);

        //This will restrict from changing contents in the table
        tblItem.setDefaultEditor(Object.class, null);

           
        //This will display the current time
        CurrentTime();

        //This will display the current date
        CurrentDate();

        //This will style the textfield
        styleUsernameField();

        
        //This will get the item details from text file to table
        getItemDetails();
        
        
        //This will get the staff's username and set it inside the textfield
        getUsername();
        
        // This class handles window closing event
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int selection = JOptionPane.showConfirmDialog(null, "Want to exit?", "Closing Staff Main Menu", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (selection == JOptionPane.YES_OPTION) {
                    new MainVMFram().setVisible(true);  
                   //This will clear the login session
                    clearStaffSession();
                    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                    dispose();
                } else {
                    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                }
            }
        });

    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblMainMenu;
    private javax.swing.JLabel lblModify;
    private javax.swing.JLabel lblRegisterStaff;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblVending;
    private javax.swing.JPanel pnlAddStaff;
    private javax.swing.JPanel pnlHistory;
    private javax.swing.JPanel pnlManageItems;
    private javax.swing.JPanel pnlModifyStaff;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
